name: "JFrog Integration Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: Adding link to JPD
        run: echo '![GitHub Logo](https://my-repo-1987.s3.us-east-2.amazonaws.com/test1.jpg?q=2)' >> $GITHUB_STEP_SUMMARY

#      - name: failing
#        run: exit 1
